version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      # MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run
      - run: echo 'export PRO_SPECIAL_BUILD="early-access"' >> $BASH_ENV
      - run: java pro_wrapper.java version
      - run: ./pro/bin/pro version
      - run: ./pro/bin/pro
