version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      # MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run
      - run: export PRO_SPECIAL_BUILD='early-access'
      - run: java pro_wrapper version
      - run: ./pro/bin/pro version
      - run: ./pro/bin/pro
